### PyTorch 张量（Tensor）
张量是一个多维数组，可以是标量、向量、矩阵或更高维度的数据结构。

在 PyTorch 中，张量（Tensor）是数据的核心表示形式，类似于 NumPy 的多维数组，但具有更强大的功能，例如支持 GPU 加速和自动梯度计算。

张量支持多种数据类型（整型、浮点型、布尔型等）。

张量可以存储在 CPU 或 GPU 中，GPU 张量可显著加速计算。

--- 

| 方法                     | 说明                                             | 示例代码                                   |
|--------------------------|--------------------------------------------------|-------------------------------------------|
| `torch.tensor(data)`     | 从 Python 列表或 NumPy 数组创建张量。            | `x = torch.tensor([[1, 2], [3, 4]])`      |
| `torch.zeros(size)`      | 创建一个全为零的张量。                           | `x = torch.zeros((2, 3))`                 |
| `torch.ones(size)`       | 创建一个全为 1 的张量。                          | `x = torch.ones((2, 3))`                  |
| `torch.empty(size)`      | 创建一个未初始化的张量。                         | `x = torch.empty((2, 3))`                 |
| `torch.rand(size)`       | 创建一个服从均匀分布的随机张量，值在 [0, 1)。    | `x = torch.rand((2, 3))`                  |
| `torch.randn(size)`      | 创建一个服从正态分布的随机张量，均值为 0，标准差为 1。 | `x = torch.randn((2, 3))`             |
| `torch.arange(start, end, step)` | 创建一个一维序列张量，类似于 Python 的 range。 | `x = torch.arange(0, 10, 2)`             |
| `torch.linspace(start, end, steps)` | 创建一个在指定范围内等间隔的序列张量。      | `x = torch.linspace(0, 1, 5)`            |
| `torch.eye(size)`        | 创建一个单位矩阵（对角线为 1，其他为 0）。       | `x = torch.eye(3)`                       |
| `torch.from_numpy(ndarray)` | 将 NumPy 数组转换为张量。                      | `x = torch.from_numpy(np.array([1, 2, 3]))` |

使用 torch.tensor() 函数，你可以将一个列表或数组转换为张量：

In [2]:
import torch 

tensor=torch.tensor([1,2,3])

print(tensor)

tensor([1, 2, 3])


如果你有一个 NumPy 数组，可以使用 torch.from_numpy() 将其转换为张量：

In [3]:
import numpy as np

np_array=np.array([1,2,3])
tensor=torch.from_numpy(np_array)
print(tensor)

tensor([1, 2, 3], dtype=torch.int32)


创建 2D 张量（矩阵）：

In [5]:
import torch

tensor_2d=torch.tensor(
  [[-9, 4, 2, 5, 7],
  [3, 0, 12, 8, 6],
  [1, 23, -6, 45, 2],
  [22, 3, -1, 72, 6]]
)

print("2D Tensor (Matrix):\n", tensor_2d)
print("Shape:", tensor_2d.shape)  # 形状

2D Tensor (Matrix):
 tensor([[-9,  4,  2,  5,  7],
        [ 3,  0, 12,  8,  6],
        [ 1, 23, -6, 45,  2],
        [22,  3, -1, 72,  6]])
Shape: torch.Size([4, 5])


### 张量的属性
张量的属性如下表：

| 属性/方法          | 说明                                   | 示例                     |
|--------------------|----------------------------------------|--------------------------|
| `.shape`           | 获取张量的形状                         | `tensor.shape`           |
| `.size()`          | 获取张量的形状                         | `tensor.size()`          |
| `.dtype`           | 获取张量的数据类型                     | `tensor.dtype`           |
| `.device`          | 查看张量所在的设备 (CPU/GPU)           | `tensor.device`          |
| `.dim()`           | 获取张量的维度数                       | `tensor.dim()`           |
| `.requires_grad`   | 是否启用梯度计算                       | `tensor.requires_grad`   |
| `.numel()`         | 获取张量中的元素总数                   | `tensor.numel()`         |
| `.is_cuda`         | 检查张量是否在 GPU 上                  | `tensor.is_cuda`         |
| `.T`               | 获取张量的转置（适用于 2D 张量）       | `tensor.T`               |
| `.item()`          | 获取单元素张量的值                     | `tensor.item()`          |
| `.is_contiguous()` | 检查张量是否连续存储                   | `tensor.is_contiguous()` |

In [9]:
import torch  

#创建一个二维的张量
tensor=torch.tensor([[1,2,3],[4,5,6]])

#张量的属性
print("Tensor:",tensor)
print("Tensor.shape:",tensor.shape)
print("Tensor.size():",tensor.size())
print("Tensor.dtype:",tensor.dtype)
print("Tensor.T",tensor.T)

Tensor: tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor.shape: torch.Size([2, 3])
Tensor.size(): torch.Size([2, 3])
Tensor.dtype: torch.int64
Tensor.T tensor([[1, 4],
        [2, 5],
        [3, 6]])


### 张量的操作
张量操作方法说明如下。

| 操作                     | 说明                                       | 示例代码                     |
|--------------------------|--------------------------------------------|------------------------------|
| `+, -, *, /`             | 元素级加法、减法、乘法、除法               | `z = x + y`                  |
| `torch.matmul(x, y)`      | 矩阵乘法                                   | `z = torch.matmul(x, y)`     |
| `torch.dot(x, y)`         | 向量点积（仅适用于 1D 张量）               | `z = torch.dot(x, y)`        |
| `torch.sum(x)`            | 求和                                       | `z = torch.sum(x)`           |
| `torch.mean(x)`           | 求均值                                     | `z = torch.mean(x)`          |
| `torch.max(x)`            | 求最大值                                   | `z = torch.max(x)`           |
| `torch.min(x)`            | 求最小值                                   | `z = torch.min(x)`           |
| `torch.argmax(x, dim)`    | 返回最大值的索引（指定维度）               | `z = torch.argmax(x, dim=1)` |
| `torch.softmax(x, dim)`   | 计算 softmax（指定维度）                   | `z = torch.softmax(x, dim=1)`|
| **形状操作**             |                                            |                              |
| `torch.reshape(x, shape)` | 改变张量形状                               | `z = torch.reshape(x, (2,3))`|
| `torch.squeeze(x)`        | 移除长度为 1 的维度                        | `z = torch.squeeze(x)`       |
| `torch.unsqueeze(x, dim)` | 在指定维度增加长度为 1 的维度              | `z = torch.unsqueeze(x, 0)`  |
| `torch.transpose(x, dim0, dim1)` | 交换两个维度                      | `z = torch.transpose(x, 0, 1)`|
| `torch.cat([x, y], dim)`  | 沿指定维度拼接张量                         | `z = torch.cat([x, y], dim=0)`|
| `torch.stack([x, y], dim)`| 沿新维度堆叠张量                           | `z = torch.stack([x, y], dim=0)` |

### 形状操作

| 操作                     | 说明                                       | 示例代码                     |
|--------------------------|--------------------------------------------|------------------------------|
| `x.view(shape)`           | 改变张量的形状（不改变数据）               | `z = x.view(3, 4)`           |
| `x.reshape(shape)`        | 类似于 `view`，但更灵活                    | `z = x.reshape(3, 4)`        |
| `x.t()`                   | 转置矩阵                                   | `z = x.t()`                  |
| `x.unsqueeze(dim)`        | 在指定维度添加一个维度                     | `z = x.unsqueeze(0)`         |
| `x.squeeze(dim)`          | 去掉指定维度为 1 的维度                    | `z = x.squeeze(0)`           |
| `torch.cat((x, y), dim)`  | 按指定维度连接多个张量                     | `z = torch.cat((x, y), dim=1)`|

In [ ]:
import torch

# 创建一个 2D 张量
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print("原始张量:\n", tensor)

# 1. **索引和切片操作**
print("\n【索引和切片】")
print("获取第一行:", tensor[0])  # 获取第一行
print("获取第一行第一列的元素:", tensor[0, 0])  # 获取特定元素
print("获取第二列的所有元素:", tensor[:, 1])  # 获取第二列所有元素

# 2. **形状变换操作**
print("\n【形状变换】")
reshaped = tensor.view(3, 2)  # 改变张量形状为 3x2
print("改变形状后的张量:\n", reshaped)
flattened = tensor.flatten()  # 将张量展平成一维
print("展平后的张量:\n", flattened)

# 3. **数学运算操作**
print("\n【数学运算】")
tensor_add = tensor + 10  # 张量加法
print("张量加 10:\n", tensor_add)
tensor_mul = tensor * 2  # 张量乘法
print("张量乘 2:\n", tensor_mul)
tensor_sum = tensor.sum()  # 计算所有元素的和
print("张量元素的和:", tensor_sum.item())

# 4. **与其他张量的操作**
print("\n【与其他张量操作】")
tensor2 = torch.tensor([[1, 1, 1], [1, 1, 1]], dtype=torch.float32)
print("另一个张量:\n", tensor2)
tensor_dot = torch.matmul(tensor, tensor2.T)  # 张量矩阵乘法
print("矩阵乘法结果:\n", tensor_dot)

# 5. **条件判断和筛选**
print("\n【条件判断和筛选】")
mask = tensor > 3  # 创建一个布尔掩码
print("大于 3 的元素的布尔掩码:\n", mask)
filtered_tensor = tensor[tensor > 3]  # 筛选出符合条件的元素
print("大于 3 的元素:\n", filtered_tensor)

# 6. 最大值索引
# 在 dim=1 维度（行内）找到最大值的索引
tensor_max= torch.argmax(tensor, dim=1)  #行的最大索引    dim=1说明按照列来操作
print("原始张量 x:",tensor)
print("最大值索引 tensor_max (dim=1):",tensor_max)


# 在 dim=1 维度（行内）计算 softmax
tensor_softmax = torch.softmax(tensor, dim=1)  
print("原始张量 tensor:",tensor)
print("softmax 结果  (dim=1):",tensor_softmax)



原始张量:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

【索引和切片】
获取第一行: tensor([1., 2., 3.])
获取第一行第一列的元素: tensor(1.)
获取第二列的所有元素: tensor([2., 5.])

【形状变换】
改变形状后的张量:
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
展平后的张量:
 tensor([1., 2., 3., 4., 5., 6.])

【数学运算】
张量加 10:
 tensor([[11., 12., 13.],
        [14., 15., 16.]])
张量乘 2:
 tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
张量元素的和: 21.0

【与其他张量操作】
另一个张量:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
矩阵乘法结果:
 tensor([[ 6.,  6.],
        [15., 15.]])

【条件判断和筛选】
大于 3 的元素的布尔掩码:
 tensor([[False, False, False],
        [ True,  True,  True]])
大于 3 的元素:
 tensor([4., 5., 6.])
原始张量 x: tensor([[1., 2., 3.],
        [4., 5., 6.]])
最大值索引 tensor_max (dim=1): tensor([2, 2])
原始张量 tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])
softmax 结果  (dim=1): tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


## Softmax 计算公式

Softmax 是一种常用的激活函数，通常用于多分类问题中，将输入值转换为概率分布。其计算公式如下：

$$
\text{softmax}(x_i) = \frac{\exp(x_i)}{\sum_{j=1}^{n} \exp(x_j)}
$$

其中：
- $ x_i $: 输入张量中的某个元素。
- $ \exp(x_i) $: 指数函数，$ e^{x_i} $。
- $ \sum_{j=1}^{n} \exp(x_j) $: 同一维度上所有元素的指数和。
- $ n $: 同一维度上的元素总数。

#### 特性
1. **范围**: Softmax 输出的每个值都在 $[0, 1]$ 范围内。
2. **归一化**: 同一维度上的输出值之和为 1，形成一个概率分布。

#### 示例
假设输入张量为 $ x = [x_1, x_2, x_3] $，则 softmax 的计算过程如下：

$$
\text{softmax}(x_1) = \frac{\exp(x_1)}{\exp(x_1) + \exp(x_2) + \exp(x_3)}
$$
$$
\text{softmax}(x_2) = \frac{\exp(x_2)}{\exp(x_1) + \exp(x_2) + \exp(x_3)}
$$
$$
\text{softmax}(x_3) = \frac{\exp(x_3)}{\exp(x_1) + \exp(x_2) + \exp(x_3)}
$$

最终输出为：

$$
\text{softmax}(x) = [\text{softmax}(x_1), \text{softmax}(x_2), \text{softmax}(x_3)]
$$

#### 应用场景
- 多分类任务中，用于计算每个类别的概率。
- 神经网络的最后一层，结合交叉熵损失函数使用。

### 张量与 NumPy 的互操作

| 操作                     | 说明                                   | 示例代码                          |
|--------------------------|----------------------------------------|-----------------------------------|
| `torch.from_numpy(ndarray)` | 将 NumPy 数组转换为张量。              | `x = torch.from_numpy(np_array)` |
| `x.numpy()`               | 将张量转换为 NumPy 数组（仅限 CPU 张量）。 | `np_array = x.numpy()`           |

In [13]:
import torch
import numpy as np

# 1. NumPy 数组转换为 PyTorch 张量
print("1. NumPy 转为 PyTorch 张量")
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print("NumPy 数组:\n", numpy_array)

# 使用 torch.from_numpy() 将 NumPy 数组转换为张量
tensor_from_numpy = torch.from_numpy(numpy_array)
print("转换后的 PyTorch 张量:\n", tensor_from_numpy)

# 修改 NumPy 数组，观察张量的变化（共享内存）
numpy_array[0, 0] = 100
print("修改后的 NumPy 数组:\n", numpy_array)
print("PyTorch 张量也会同步变化:\n", tensor_from_numpy)

# 2. PyTorch 张量转换为 NumPy 数组
print("\n2. PyTorch 张量转为 NumPy 数组")
tensor = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.float32)
print("PyTorch 张量:\n", tensor)

# 使用 tensor.numpy() 将张量转换为 NumPy 数组
numpy_from_tensor = tensor.numpy()
print("转换后的 NumPy 数组:\n", numpy_from_tensor)

# 修改张量，观察 NumPy 数组的变化（共享内存）
tensor[0, 0] = 77
print("修改后的 PyTorch 张量:\n", tensor)
print("NumPy 数组也会同步变化:\n", numpy_from_tensor)

# 3. 注意：不共享内存的情况（需要复制数据）
print("\n3. 使用 clone() 保证独立数据")
tensor_independent = torch.tensor([[13, 14, 15], [16, 17, 18]], dtype=torch.float32)
numpy_independent = tensor_independent.clone().numpy()  # 使用 clone 复制数据
print("原始张量:\n", tensor_independent)
tensor_independent[0, 0] = 0  # 修改张量数据
print("修改后的张量:\n", tensor_independent)
print("NumPy 数组（不会同步变化）:\n", numpy_independent)

1. NumPy 转为 PyTorch 张量
NumPy 数组:
 [[1 2 3]
 [4 5 6]]
转换后的 PyTorch 张量:
 tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
修改后的 NumPy 数组:
 [[100   2   3]
 [  4   5   6]]
PyTorch 张量也会同步变化:
 tensor([[100,   2,   3],
        [  4,   5,   6]], dtype=torch.int32)

2. PyTorch 张量转为 NumPy 数组
PyTorch 张量:
 tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
转换后的 NumPy 数组:
 [[ 7.  8.  9.]
 [10. 11. 12.]]
修改后的 PyTorch 张量:
 tensor([[77.,  8.,  9.],
        [10., 11., 12.]])
NumPy 数组也会同步变化:
 [[77.  8.  9.]
 [10. 11. 12.]]

3. 使用 clone() 保证独立数据
原始张量:
 tensor([[13., 14., 15.],
        [16., 17., 18.]])
修改后的张量:
 tensor([[ 0., 14., 15.],
        [16., 17., 18.]])
NumPy 数组（不会同步变化）:
 [[13. 14. 15.]
 [16. 17. 18.]]
